
server:
  servlet:
    context-path: /app

spring:
  profiles:
    active:
    - dev
  application:
    name: ECOMMERCE-MONOLITHIC-BACKEND-APP
  mail:
    host: smtp.gmail.com
    port: 587
    username: springabcxyzboot@gmail.com
    password: A4815162342z
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

twilio:
  account_sid: AC8f26f7a745d667b1f2b49601e188b300
  auth_token: 8e1833795a9b8f464ac12ae4df83c0cc # fake...
  trial_number: +15093944881



